# Generated by Django 3.2 on 2021-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210426_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchEatMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding eat'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchEatMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding eat'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchHappyMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding happy'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchHappyMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding happy'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchHealthMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding health'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='howMuchHealthMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding health'),
        ),
        migrations.AlterField(
            model_name='eat_activity',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price of eat'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchEatMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding eat'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchEatMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding eat'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchHappyMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding happy'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchHappyMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding happy'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchHealthMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding health'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='howMuchHealthMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding health'),
        ),
        migrations.AlterField(
            model_name='happy_activity',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price of Happy'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchEatMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding eat'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchEatMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding eat'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchHappyMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding happy'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchHappyMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding happy'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchHealthMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding health'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='howMuchHealthMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding health'),
        ),
        migrations.AlterField(
            model_name='health_activity',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price of Health'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='howMuchRating',
            field=models.IntegerField(default=0, verbose_name='Count of adding rating'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='unlockRating',
            field=models.IntegerField(verbose_name='Min rating for unlock'),
        ),
        migrations.AlterField(
            model_name='learning_params',
            name='howMuchRating',
            field=models.IntegerField(default=0, verbose_name='Count of adding rating'),
        ),
        migrations.AlterField(
            model_name='learning_params',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Min count of adding money'),
        ),
        migrations.AlterField(
            model_name='learning_params',
            name='unlockRating',
            field=models.IntegerField(verbose_name='Min rating for unlock'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='HowMuchEarningsMax',
            field=models.IntegerField(default=0, verbose_name='Max count of adding money'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='HowMuchEarningsMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding money'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchEatMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding eat'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchEatMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding eat'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchHappyMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding happy'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchHappyMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding happy'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchHealthMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding health'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='howMuchHealthMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding health'),
        ),
        migrations.AlterField(
            model_name='normalworks',
            name='unlockRating',
            field=models.IntegerField(verbose_name='Min rating for unlock'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='age',
            field=models.IntegerField(max_length=150, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='eat_level',
            field=models.IntegerField(verbose_name='Happy level'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='happy_level',
            field=models.IntegerField(verbose_name='Happy level'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='health_level',
            field=models.IntegerField(verbose_name='Happy level'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='items',
            field=models.IntegerField(default=10, verbose_name='Count of bottles'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='money',
            field=models.IntegerField(default=500, verbose_name='Money'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='HowMuchEarningsItemsMax',
            field=models.IntegerField(default=0, verbose_name='Max count of adding Items'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='HowMuchEarningsItemsMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding Items'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='HowMuchEarningsMax',
            field=models.IntegerField(default=0, verbose_name='Max count of adding money'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='HowMuchEarningsMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding money'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchEatMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding eat'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchEatMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding eat'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchHappyMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding happy'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchHappyMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding happy'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchHealthMax',
            field=models.IntegerField(default=1, verbose_name='Max count of adding health'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='howMuchHealthMin',
            field=models.IntegerField(default=0, verbose_name='Min count of adding health'),
        ),
        migrations.AlterField(
            model_name='personageworks',
            name='unlockRating',
            field=models.IntegerField(verbose_name='Min rating for unlock'),
        ),
        migrations.AlterField(
            model_name='transports',
            name='howMuchRating',
            field=models.IntegerField(default=0, verbose_name='Count of adding rating'),
        ),
        migrations.AlterField(
            model_name='transports',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transports',
            name='unlockRating',
            field=models.IntegerField(verbose_name='Min rating for unlock'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.IntegerField(unique=True),
        ),
    ]
