# Generated by Django 3.2 on 2021-04-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210426_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Character',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.personage'),
        ),
    ]
