# Generated by Django 3.2 on 2021-04-26 15:36

import MainApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_user_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Character',
            field=models.OneToOneField(default=MainApp.models.Personage.get_new, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainApp.personage'),
        ),
    ]
