# Generated by Django 3.2 on 2021-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_user_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
