# Generated by Django 3.2 on 2021-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_personage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
